### ISSUE TITLE
Jobs not working with webhook

### ISSUE THREAD

**Issue by 190ba** [mvisonneau/gitlab-ci-pipelines-exporter#184]
Hey @mvisonneau,

First, thank you for this great project :)

I'm currently facing an issue with a configuration with Gitlab sending webhooks to the exporter, hosted in AKS
Pipeline events are correctly,exported, though i'm not sure whether they are pushed or pulled :
`{"environments-count":0,"level":"info","msg":"scheduling metrics pull","refs-count":60,"time":"2020-11-20T16:16:05Z"}`

Regarding the Job events, I have these errors in the logs, and no metrics showing in Grafana
`{"event-type":"*gitlab.JobEvent","ip-address":"10.1.0.67:43490","level":"warning","msg":"received a non supported event type as a webhook","time":"2020-11-20T16:15:37Z","user-agent":""}`

Here is the conf I used :

```
  gitlab:
    url: https://gitlab.blablabla

    token: "{{ gitlab__token }}"
  wildcards:
      owner:
        name: me
        kind: user
        include_subgroups: true
      pull:
      refs:
        regexp: ".*"
      pipeline:
        jobs:
          enabled: true
```

Could you help me on this part please ?
And could you confirm the "pull" section in configuration file also apply to webhook ?

Thanks a lot
Regards
Igor

**Comment by mvisonneau** [comment]
Hey @190ba, thank you for the kind feedback! 🙇 

Regarding your issue, indeed, only pipeline and deployment events are supported. Even if you want/need jobs metrics, using pipeline events will be good enough as they are generated on each job changes. 

In your config, the only thing supplementary required in order to get push support is the following:

```yaml
server:
  webhook:
    enabled: true
    secret_token: <strong_arbitrary_secret_token>

wildcards / projects matching the ones expected to send events
``` 

hope this helps!

**Comment by mvisonneau** [comment]
the example config is a good start actually: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/examples/webhooks/gitlab-ci-pipelines-exporter/config.yml

**Comment by mvisonneau** [comment]
I assume that your problem is solved @190ba, feel free to reopen if necessary 👍

**Comment by strowi** [comment]
Hi,

sorry to reopen, but it seems i'm running into the same issue with v0.4.6. Webhook works, but metrics-pull still gets scheduled..?

```yaml
server:
  webhook:
    enabled: true
    secret_token: xyz=

gitlab:
  url: https://git.xyz.net

wildcards:
  - owner:
      name: sys
      kind: group
      include_subgroups: true
    pull:
    refs:
      regexp: ".*"
    pipeline:
      jobs:
        enabled: true
```
gives the following logs:
```
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="exporter configured" gitlab-endpoint="https://git.xyz.net" pull-environments-from-projects-interval=1800s pull-metrics-interval=30s pull-projects-from-wildcards-interval=1800s pull-rate-limit=10rps pull-refs-from-projects-interval=300s
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling projects from wildcards pull" wildcards-count=1
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling environments from projects pull" projects-count=0
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling refs from projects pull" projects-count=0
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling metrics pull" environments-count=0 refs-count=0
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="http server started" listen-address=":8080" metrics-endpoint-enabled=true pprof-endpoint-enabled=false webhook-endpoint-enabled=true
gitlab-ci-exporter_1  | time="2021-01-27T20:56:45Z" level=info msg="discovered new project" project-name=sys/renovate wildcard-archived=false wildcard-owner-include-subgroups=true wildcard-owner-kind=group wildcard-owner-name=sys wildcard-search=
...
gitlab-ci-exporter_1  | time="2021-01-27T20:59:34Z" level=info msg="scheduling metrics pull" environments-count=0 refs-count=5
```

regards,
strowi

**Comment by mvisonneau** [comment]
👋 hey @strowi,

indeed, apologies if this is unclear, basically if you want to disable the pull, you will need to add the following to your config:

```yaml
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false
```

**Comment by strowi** [comment]
Hi @mvisonneau,

thx for clearing this up. I see no logs scheduling anything now.
But the projects are all ignored when using the wildcards option with a log like this:

```
gitlab-ci-exporter_1  | time="2021-01-28T09:50:34Z" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=sys/runbook ref=master ref-kind=branch
```

BTW shouldn't it be possible to remove the project/wildcard option completely, since the webhook-payload contains those infos? Or is it a security measure to only allow specific gitlab-projects/instances?

**Comment by mvisonneau** [comment]
absolutely, this is currently the behaviour in order to avoid fetching non desired projects or refs. eg: when you configure the hook at the group level but only need a few projects under this group. We could definitely reevaluate it though. For now you will need to have a matching project/wildcard in place.

**Comment by mvisonneau** [comment]
I updated the [examples/webhooks](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/562759d7cd9207b5b8148848968bc101efd9a235) to make it clearer btw 👍

**Comment by strowi** [comment]
Good to know.;)

Shouldn't this disable the pull, but allow the webhook for `sys/*` (at least when using pull the wildcard matches)?

```yaml
server:
  webhook:
    enabled: true
    secret_token: xyz=

gitlab:
  url: https://git.xyz.net

wildcards:
  - owner:
      name: sys
      kind: group
      include_subgroups: true
    pull:
    refs:
      regexp: ".*"
    pipeline:
      jobs:
        enabled: true

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false
```

But as written above, it seems to ignore e.g. 'sys/runbook'..

```
gitlab-ci-exporter_1  | time="2021-01-28T09:50:34Z" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=sys/runbook ref=master ref-kind=branch

```

**Comment by mvisonneau** [comment]
if believe there is an identation error on your wildcard definition, it should be:

```yaml
wildcards:
  - owner:
      name: sys
      kind: group
      include_subgroups: true
    pull:
      refs:
        regexp: ".*"
      pipeline:
        jobs:
          enabled: true
```

**Comment by mvisonneau** [comment]
I believe I am going to review a bit the attributes hierachy as it also seems a bit confusing 👍

**Comment by strowi** [comment]
Yes there was, but fixing it didin't change the outcome:

```
gitlab-ci-exporter_1  | time="2021-01-28T10:33:43Z" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=sys/runbook ref=master ref-kind=branch
```
Still trying to figure out the error...

**Comment by strowi** [comment]
Ah, it seems setting `on_init: true` for projects + refs fixes _something_. ;) 
Haven't looked into the code so far, but maybe there is an empty var so nothing to compare to, when using the webhook?

```
pull:
  projects_from_wildcards:
    on_init: true
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: true
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

```

**Comment by mvisonneau** [comment]
hmm 🤔 which version of the exporter are you using ?

it is strange indeed, actually you shouldn't even need the

```yaml
pull:
  refs:
    regexp: ".*"
```

as the default is `^main|master$`

**Comment by strowi** [comment]
i'm using v0.4.6. Also tried different combinations of refs-regex or without.. it never ack'd the master-branch.

Not sure how i can help further..  Now i continued configuring a redis for HA/Cache i can switch to the above config.. but on a fresh setup the webhook never triggered a pull..

**Comment by mvisonneau** [comment]
Thanks for the confirmation @strowi, I believe I found the issue, it has to do with the fact it is a wildcard. if the project is statically configured it works. I'll try to provide a fix for this unexpected behaviour 👍

**Comment by mvisonneau** [comment]
ok this should be fixed with https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/142f0d4576b34e710b7e55cfa3ae08da925bd100 :)

**Comment by strowi** [comment]
Thx! 
The webhook seems to trigger a discovery of all projects. 
Not sure if that is intended though. But it works for our use-case .;)

```
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="exporter configured" gitlab-endpoint="https://git.xyz.net" pull-rate-limit=10rps
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="pull projects from wildcards" on-init=no scheduled=no
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="pull environments from projects" on-init=no scheduled=no
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="pull refs from projects" on-init=no scheduled=no
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="pull metrics" on-init=no scheduled=no
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="garbage collect projects" on-init=no scheduled="every 14400s"
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="garbage collect environments" on-init=no scheduled="every 14400s"
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="garbage collect refs" on-init=no scheduled="every 1800s"
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="garbage collect metrics" on-init=no scheduled="every 300s"
exporter_1  | time="2021-01-29T09:46:59Z" level=info msg="http server started" listen-address=":8080" metrics-endpoint-enabled=true openmetrics-encoding-enabled=false pprof-endpoint-enabled=false webhook-endpoint-enabled=true
exporter_1  | time="2021-01-29T09:47:40Z" level=info msg="project ref not currently exported but its configuration matches a wildcard, triggering a pull of the projects from this wildcard" project-name=sys/runbook ref=master ref-kind=branch
exporter_1  | time="2021-01-29T09:47:48Z" level=info msg="discovered new project" project-name=sys/ci/renovate wildcard-archived=false wildcard-owner-include-subgroups=false wildcard-owner-kind= wildcard-owner-name= wildcard-search=
exporter_1  | time="2021-01-29T09:47:48Z" level=info msg="discovered new project" project-name=sys/logging/filebeat-oss wildcard-archived=false wildcard-owner-include-subgroups=false wildcard-owner-kind= wildcard-owner-name= wildcard-search=
...


```

**Comment by mvisonneau** [comment]
yep that is expected, I took a shortcut here, this not very optimized 😅

**Comment by BilalAslam1** [comment]
Is there any timeline for adding support for not triggering a discovery of all projects with a web hook. And, to not fetch refs for projects if the project_defaults.pull.refs.branches.regexp is left blank or to match on anything.

In the use case, that someone wants to collect metrics for all incoming web hooks in a group without having to discovery all the projects (something like checking if the webhook project.path_with_namespace contains wildcards.owner.name) and their subsequent refs.
